version = 0.1

[default.global.parameters]
stack_name = "otpOnLambda"

[default.deploy]
[default.deploy.parameters]
s3-bucket = "dev-sam-deploy-dataninja"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lqc84x4yoesx"
s3_prefix = "otpOnLambda"
region = "ap-southeast-1"
disable_rollback = true
image_repositories = []
