AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Sam Template

Globals:
  Function:
    Timeout: 900


Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "OTP-FastAPI"
      MemorySize: 128
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Environment:
        Variables:
          EMAIL_SENDER: 'CHANGE_THIS'
          EMAIL_PASSWORD: 'CHANGE_THIS'
          MY_SALT: 'CHANGE_THIS'
          MY_SECRET_KEY: 'CHANGE_THIS'

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'